# -*- coding: utf-8 -*-
"""Streamlit.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-2iKB1YBvErarm09y9FTWUboOhe8zBB

#Question 1:
"""

import streamlit as st

st.text("Hello world")

!streamlit run /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py

"""#Question 2:"""

colors = ["Green", "Yellow", "Red", "Blue"]
default_colors = ["Yellow", "Red"]
options = st.multiselect("Your favorite colors:",
                         colors, default=default_colors)
st.write("You selected:", options)

"""#Question 3:"""

st.text_input("User:")

"""#Question 4:"""

st.image(image_path, caption='A cat', width='RGB', channels='BGR')

"""#Question 5:"""

def levenshtein_distance(token1, token2):
    distances = [[0]*(len(token2)+1) for _ in range(len(token1)+1)]

    for t1 in range(len(token1) + 1):
        distances[t1][0] = t1

    for t2 in range(len(token2) + 1):
        distances[0][t2] = t2

    a = 0
    b = 0
    c = 0

    for t1 in range(1, len(token1) + 1):
        for t2 in range(1, len(token2) + 1):
            if (token1[t1-1] == token2[t2-1]):
                distances[t1][t2] = distances[t1 - 1][t2 - 1]
            else:
                a = distances[t1][t2 - 1]
                b = distances[t1 - 1][t2]
                c = distances[t1 - 1][t2 - 1]

                if (a <= b and a <= c):
                    distances[t1][t2] = a + 1
                elif (b <= a and b <= c):
                    distances[t1][t2] = b + 1
                else:
                    distances[t1][t2] = c + 1

    return distances[len(token1)][len(token2)]
print(levenshtein_distance("elmets", "elements"))

"""#Question 6:"""

st.session_state

"""#Question 7:"""

import streamlit as st

with st.form("my_form"):
    col1, col2 = st.columns(2)
    f_name = col1.text_input('First Name')
    l_name = col2.text_input('Last Name')
    submitted = st.form_submit_button("Submit")

    if submitted:
        st.write("First Name:", f_name, " - Last Name:", l_name)

"""#Question 8:"""

uploaded_files = st.file_uploader("Choose files", accept_multiple_files=True)

"""#Question 9:"""

st.slider()

"""#Question 10:"""